name: Release Build

on:
  push:
    tags:
      - 'v*'

env:
  AUTO_TAG: latest
  AUTO_TITLE: Latest Build

jobs:
  release_build:
    name: Release Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock', '**/package-lock.json') }}

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Update Current Release
        id: update_current
        uses: Trinovantes/action-automatic-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          is_prerelease: false

      - name: Upload Asset to Current Release
        uses:  Trinovantes/action-release-upload@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.update_current.outputs.release_id }}
          upload_url: ${{ steps.update_current.outputs.upload_url }}
          files: ./dist/*.user.js

      - name: Update Latest Build Release
        id: update_latest
        uses: Trinovantes/action-automatic-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          auto_release_tag: ${{ env.AUTO_TAG }}
          auto_release_title: ${{ env.AUTO_TITLE }}
          is_prerelease: false

      - name: Upload Asset to Latest Build Release
        uses:  Trinovantes/action-release-upload@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.update_latest.outputs.release_id }}
          upload_url: ${{ steps.update_latest.outputs.upload_url }}
          files: ./dist/*.user.js
