name: Upgrade Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  upgrade:
    name: Upgrade Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('**/yarn.lock', '**/package-lock.json') }}

      - name: Upgrade dependencies
        run: yarn upgrade

      - name: Run linter
        run: yarn lint

      - name: Commit changes
        run: |
          git config --global user.name 'Upgrade Dependencies Workflow'
          git config --global user.email '<>'
          git add yarn.lock
          git commit -m "Upgrade Dependencies $(date -u)" || true
          git push
